spring:
  application:
    name: admin-server
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    non-secure-port: ${server.port}
    secure-port-enabled: false