version: '3.8'

services:
  # Database for User Service
  user-db:
    image: postgres:latest
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - task-network

  # Database for Task Service
  task-db:
    image: postgres:latest
    container_name: task-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5434:5432"
    volumes:
      - task-data:/var/lib/postgresql/data
    networks:
      - task-network

  # Database for Notification Service
  notification-db:
    image: postgres:latest
    container_name: notification-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notify
    ports:
      - "5435:5432"
    volumes:
      - notification-data:/var/lib/postgresql/data
    networks:
      - task-network

  # Eureka Server
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - task-network

  # Spring Boot Admin Server
  admin-server:
    build: ./admin-server
    container_name: admin-server
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      EUREKA_URL: http://eureka-server:8761/eureka/
      HOSTNAME: admin-server
      SERVICE_URL: http://admin-server:9090
    depends_on:
      - eureka-server
    networks:
      - task-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      HOSTNAME: api-gateway
      ADMIN_URL: http://admin-server:9090
      FRONTEND_URL: http://frontend:5173
      SERVICE_URL: http://api-gateway:8080
    depends_on:
      - eureka-server
      - admin-server
      - user-service
      - notification-service
      - task-service
    networks:
      - task-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      DATASOURCE.URL: jdbc:postgresql://user-db:5432/userdb
      DATASOURCE.USERNAME: postgres
      DATASOURCE.PASSWORD: postgres
      HOSTNAME: user-service
      ADMIN_URL: http://admin-server:9090
      SERVICE_URL: http://user-service:8081
    depends_on:
      - eureka-server
      - user-db
      - admin-server
    networks:
      - task-network

  # Task Service
  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8082:8082"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      DATASOURCE.URL: jdbc:postgresql://task-db:5432/taskdb
      DATASOURCE.USERNAME: postgres
      DATASOURCE.PASSWORD: postgres
      HOSTNAME: task-service
      ADMIN_URL: http://localhost:9090
      SERVICE_URL: http://task-service:8082
    depends_on:
      - eureka-server
      - task-db
      - admin-server
    networks:
      - task-network

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
      DATASOURCE.URL: jdbc:postgresql://notification-db:5432/notify
      DATASOURCE.USERNAME: postgres
      DATASOURCE.PASSWORD: postgres
      HOSTNAME: notification-service
      ADMIN_URL: http://admin-server:9090
      SERVICE_URL: http://notification-service:8083
    depends_on:
      - eureka-server
      - notification-db
      - admin-server
    networks:
      - task-network

  # Frontend
  frontend:
    build: ./react-app
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_GATEWAY_URL=http://api-gateway:8080
    depends_on:
      - api-gateway
    networks:
      - task-network

volumes:
  user-data:
  task-data:
  notification-data:

networks:
  task-network:
    driver: bridge