spring:
  application:
    name: api-gateway
  boot:
    admin:
      client:
        url: ${ADMIN_URL:http://localhost:9090}
        instance:
          service-base-url: ${GATEWAY_SERVICE_URL:http://localhost:8080}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          httpclient:
            websocket:
              max-frame-payload-length: 65536
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${JWKS_URI:http://localhost:8085/auth/.well-known/jwks.json}
  frontend:
    url: ${FRONTEND_URL:http://localhost:5174}
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}
    non-secure-port: ${server.port}
    secure-port-enabled: false